### PR TITLE
Added support for webhooks using POST HTTP method

### PR DESCRIPTION
**Pull request by arekziobrowski**
There are two things I'm not sure about:

- shall we introduce some maximum size for the payload (so it's not used in a malicious way)?
- shall we somehow restrict the payload format to JSON and sanitize/validate it?

### CODE REVIEW

**Comment by modern-age-engineering** [comment]
This would be a useful feature as I was trying to figure out how to send a Slack webhook message from this plugin, but that webook looks like it expects a POST request.

**Comment by marcushyett-ph** [comment]
@arekziobrowski looks great - would be awesome if you could implement a maximum payload size restriction?

Not sure it makes sense to enforce the POST Payload to always be JSON, we could support specific content types and validate against them, but that might overkill.

**Comment by arekziobrowski** [comment]
@marcushyett-ph, do you think the maximum payload size restriction should be configurable?
I restricted it to fixed 16 kilobytes - I based that value on Slack limits, that when message payload size exceeds 16 kilobytes, the message server will disconnect client emitting such message [[source](https://api.slack.com/docs/rate-limits#posting-messages)].

**Comment by arekziobrowski** [comment]
@marcushyett-ph, could you take a look at the new changes?

**Comment by arekziobrowski** [comment]
@yakkomajuri should I close this pull request?

**Comment by arekziobrowski** [comment]
Closing due to inactivity.

**Pull request closed without merging**
